PROJECT = "hotelops-suite"
DATASET = "hotelops"

def _t(name: str) -> str:
    return f"{PROJECT}.{DATASET}.{name}"

# Fact tables
F_BANCHE_MOVIMENTI          = _t("f_banche_movimenti")
F_SALDI_BANCA_SNAPSHOT      = _t("f_saldi_banca_snapshot")
F_SALDI_BANCA_CHIUSURA_MENSILE = _t("f_saldi_banca_chiusura_mensile")
F_MOVIMENTI_CONTABILI       = _t("f_movimenti_contabili")
F_BUDGET_MENSILE            = _t("f_budget_mensile")
F_PIANO_FINANZIARIO_INPUT   = _t("f_piano_finanziario_input")
F_ACCODAMENTI               = _t("f_accodamenti")
F_BILANCINO                 = _t("f_bilancino")
F_CONSUMI_ECONOMATO         = _t("f_consumi_economato")
F_COPERTI_GIORNALIERI       = _t("f_coperti_giornalieri")
F_RICAVI_FB                 = _t("f_ricavi_fb")
F_CHIUSURA_MENSILE          = _t("f_chiusura_mensile")
F_PARTITE_APERTE_FORNITORI  = _t("f_partite_aperte_fornitori")
F_RICAVI_STORICI            = _t("f_ricavi_storici")
F_COEFFICIENTI_CONSUMO      = _t("f_coefficienti_consumo")
F_PMS_STATISTICHE           = _t("f_pms_statistiche")
F_PRODUZIONE_PMS            = _t("f_produzione_pms")
F_REVIEWS                   = _t("f_reviews")
F_PENDING_ALERT_FLAGS       = _t("f_pending_alert_flags")
F_APIFY_RUNS                = _t("f_apify_runs")
F_RISTOCUBE_ORDERS          = _t("f_ristocube_orders")
F_VENDITE_FB                = _t("f_vendite_fb")
F_FATTURE_RIGHE             = _t("f_fatture_righe")
F_PIPELINE_RUNS             = _t("f_pipeline_runs")
F_BILANCI_ANNUALI           = _t("f_bilanci_annuali")
F_PROGETTO_VOCI             = _t("f_progetto_voci")
F_PROGETTO_EVENTI           = _t("f_progetto_eventi")
F_SPIAGGIA_RESERVATIONS     = _t("f_spiaggia_reservations")
F_SPIAGGIA_CASH_FLOWS       = _t("f_spiaggia_cash_flows")
F_SPIAGGIA_SPOTS            = _t("f_spiaggia_spots")
F_SPIAGGIA_CORRISPETTIVI    = _t("f_spiaggia_corrispettivi")
F_SPIAGGIA_FB_ORDINI        = _t("f_spiaggia_fb_ordini")

# Dimension tables
D_VOCI_PIANO_FINANZIARIO    = _t("d_voci_piano_finanziario")
D_PIANO_CONTI               = _t("d_piano_conti")
D_CATEGORIE_CONTI           = _t("d_categorie_conti")
D_FORNITORI                 = _t("d_fornitori")
D_ANAGRAFICA_FORNITORI      = _t("d_anagrafica_fornitori")
D_MAPPING_PIANO_FINANZIARIO = _t("d_mapping_piano_finanziario")
D_COEFFICIENTI_STAGIONALITA = _t("d_coefficienti_stagionalita")
D_PROGETTI                  = _t("d_progetti")

# Views
V_PIANO_FINANZIARIO_MENSILE = _t("v_piano_finanziario_mensile")
V_BUDGET_VS_CONSUNTIVO      = _t("v_budget_vs_consuntivo")
V_PIANO_FINANZIARIO_CONSUNTIVO = _t("v_piano_finanziario_consuntivo")
V_PREVISIONE_CASSA          = _t("v_previsione_cassa")
V_PL_MOVIMENTI               = _t("v_pl_movimenti")
V_CASHFLOW_MENSILE           = _t("v_cashflow_mensile")
V_INCASSI_PER_CANALE         = _t("v_incassi_per_canale")
V_PROGETTO_VOCI_STATO        = _t("v_progetto_voci_stato")

# Looker Studio views
V_CONDGES_BUDGET_CONSUNTIVO  = _t("v_condges_budget_consuntivo")
V_CONDGES_PF_MENSILE         = _t("v_condges_pf_mensile")
V_CONDGES_CASHFLOW           = _t("v_condges_cashflow")
V_ECONOMATO_CONSUMI          = _t("v_economato_consumi")
V_ECONOMATO_PARETO           = _t("v_economato_pareto")
V_BUDGET                     = _t("v_budget")
V_FB_KPI                     = _t("v_fb_kpi")
V_FB_CONSUMI                 = _t("v_fb_consumi")
V_FB_RICAVI                  = _t("v_fb_ricavi")
V_FB_PASTI                   = _t("v_fb_pasti")
V_CE_MENSILE_BILANCINO       = _t("v_ce_mensile_bilancino")
